#!/usr/bin/env bash

# Checks if the light is on in the server room. Using the Tinkerforge ambient light bricklet
#
# Parameters:
# -c - Temperature that is critical (defaults to 40°C)
# -w - Temperature that is warning (defaults to 30°C)
# -h - IP or hostname of server rack monitoring brick
# -u - UID of sensor in server rack

# shellcheck source=common.sh
. "$(dirname "${0}")/common.sh"
checkName=server_rack_light

# Parameters
warn=55
crit=60

usage() {
	echo "Usage: ${0} -h <host> -u <uid> -w <warning> -c <critical>"
	exit 3
}

# Parse parameters
while getopts ":w:c:h:u:" opt; do
	case "${opt}" in
		c)
			crit="${OPTARG}"
			;;
		w)
			warn="${OPTARG}"
			;;
		h)
			host="${OPTARG}"
			;;
		u)
			uid="${OPTARG}"
			;;
		\?)
			echo "Invalid option: -${OPTARG}"
			usage
			;;
		:)
			echo "Option -${OPTARG} requires an argument"
			usage
			;;
	esac
done

light=$($(dirname "${0}")/tinkerforge --host $host call  ambient-light-v3-bricklet $uid get-illuminance | cut -d "=" -f 2)
# Format output
if [ "${light}" -gt "${crit}" ]; then
	checkState=CRITICAL
elif [ "${light}" -gt "${warn}" ]; then
	checkState=WARNING
fi
checkOutput="${light} Lux"

# Format perfdata
checkPerfdata="light=${light}Lux;${warn};${crit};0;900"

checkReturn
